# Numpy exercises 

<div class="alert alert-warning " role="alert" style="margin-top: 0px">
<h3> Question-0:</h3>
    <b>Import numpy as np and display the version and configuration.</b>
</div>

In [1]:
import numpy as np

np.version.version

'1.20.1'

In [2]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/23ris/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/23ris/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/23ris/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/23ris/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/23ris/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/23ris/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/23ris/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/23ris/anaconda3\\Library\\include']


<div class="alert alert-warning " role="alert" style="margin-top: 0px">
<h3> Question-1:</h3>
    <b>Create a null vector of size 9 whose 5<sup>th</sup> element is 9.</b>
</div>

In [3]:
a1 = np.zeros(8)
a1[4] = 8
a1

array([0., 0., 0., 0., 8., 0., 0., 0.])

<div class="alert alert-warning " role="alert" style="margin-top: 0px">
<h3> Question-2:</h3>
    <b>Create an identity matrix of order 3*3.</b>
</div>

In [4]:
# Method - 1

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# Method - 2 

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# Method - 3

def identity(order):
    idty = np.zeros(order**2).reshape(order, order)
    index = 0
    while index<order:
        idty[index][index] = 1
        index += 1
    return idty

identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<div class="alert alert-warning " role="alert" style="margin-top: 0px">
<h3> Question-3:</h3>
    <b>Create a 5*5*5 array with random values and find the minimum and maximum in each column.</b>
</div>

In [7]:
a2 = np.random.random((5,5,5))
print(a2.max(axis=1).max(axis=1))
print(a2.min(axis=1).min(axis=1))

[0.87011231 0.94725592 0.96281285 0.88786563 0.86503682]
[0.14540224 0.00133061 0.02027652 0.04248547 0.08895286]


<div class="alert alert-warning " role="alert" style="margin-top: 0px">
<h3> Question-4:</h3>
    <b>Create a 4*4 matrix with random integers and normalize the values between 0 and 1.</b>
</div>

In [8]:
a3 = np.random.randint(1,100,(4,4))
normalizer = a3.max() - a3.min()
normalized_a3 = (a3 - a3.min())/normalizer
a3

array([[48, 21,  8, 43],
       [13, 40, 97, 85],
       [ 3, 62, 62, 98],
       [89, 35, 11,  8]])

In [9]:
normalized_a3

array([[0.47368421, 0.18947368, 0.05263158, 0.42105263],
       [0.10526316, 0.38947368, 0.98947368, 0.86315789],
       [0.        , 0.62105263, 0.62105263, 1.        ],
       [0.90526316, 0.33684211, 0.08421053, 0.05263158]])

<div class="alert alert-warning " role="alert" style="margin-top: 0px">
<h3> Question-5:</h3>
    <b>Consider a random 50X2 matrix representing Cartesian Coordinates, convert them into polar coordinates.</b>
</div>

In [10]:
a4 = np.random.randint(1,100,100).reshape(50,2)
X, Y = a4[:,0], a4[:,1]
r = np.sqrt(X**2+Y**2).round(4)
T = np.arctan2(Y,X).round(4)

# printing the first 10 coordinates
for i,j,a,b in zip(X[:10],Y[:10],r[:10],T[:10]):
    print("Cartesian Coordinates {} into polar corrdinates are {}".format((i,j),(a,b)))

Cartesian Coordinates (44, 81) into polar corrdinates are (92.1792, 1.0732)
Cartesian Coordinates (35, 48) into polar corrdinates are (59.4054, 0.9408)
Cartesian Coordinates (97, 90) into polar corrdinates are (132.3216, 0.748)
Cartesian Coordinates (96, 6) into polar corrdinates are (96.1873, 0.0624)
Cartesian Coordinates (84, 98) into polar corrdinates are (129.0736, 0.8622)
Cartesian Coordinates (77, 86) into polar corrdinates are (115.434, 0.8406)
Cartesian Coordinates (88, 50) into polar corrdinates are (101.2126, 0.5167)
Cartesian Coordinates (5, 92) into polar corrdinates are (92.1358, 1.5165)
Cartesian Coordinates (23, 66) into polar corrdinates are (69.8928, 1.2355)
Cartesian Coordinates (81, 58) into polar corrdinates are (99.6243, 0.6214)


<div class="alert alert-warning " role="alert" style="margin-top: 0px">
<h3> Question-6:</h3>
    <b>Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value ?</b>
</div>

In [11]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))                   # Empty array with required no. of elements
Z0[::nz+1] = Z                                            # Replace every 4th zero with the actual element from the array
Z0

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

<div class="alert alert-warning " role="alert" style="margin-top: 0px">
<h3> Question-7:</h3>
    <b>Create a random 5*3 numpy array with and find the total memory occupied by this array. </b>
</div>

In [12]:
a4 = np.random.randint(1, 100, (5,3))
memory = a4.size * a4.itemsize       # length of the array * space occupied by each element
print(f"The memory occupied by  the\n {a4} \nis {memory} bytes")

The memory occupied by  the
 [[44 85 36]
 [31 31 37]
 [79 47 40]
 [22 98 13]
 [15 80 46]] 
is 60 bytes


<div class="alert alert-warning " role="alert" style="margin-top: 0px">
<h3> Question-8:</h3>
    <b>Generate a 4X3 array of length 12 with elements from 60-71. Iterate over the array and print the numbers individually.</b>
</div>

In [13]:
a5 = np.arange(60,72).reshape(4,3)
a5

array([[60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71]])

In [14]:
# Note: A simple for loop doesn't work. It prints all the elements column wise.

for i in a5:
    print(i)

[60 61 62]
[63 64 65]
[66 67 68]
[69 70 71]


In [15]:
# Therefore, we use the function .nditer which iterates over the n-dimensions at once

for i in np.nditer(a5):
    print(i, end=" ")

60 61 62 63 64 65 66 67 68 69 70 71 

<div class="alert alert-warning " role="alert" style="margin-top: 0px">
<h3> Question-9:</h3>
    <b>Create a 10x10 matrix, in which the elements on the borders are 1, and rest 0.</b>
</div>

In [16]:
# Method-1

a6 = np.ones((10,10))
for index, element in np.ndenumerate(a6):     # index will contain a tuple of rwo,column positions
    row, column = index[0], index[1]
    a6[index] = np.where((row==0 or row==9 or column==0 or column==9), 1, 0)
a6

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
# Method-2

a6 = np.ones((10,10))
a6[1:-1, 1:-1] = 0          # changing all the non boundary elements to 0 a[rows span, columns span]
a6

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

<div class="alert alert-warning " role="alert" style="margin-top: 0px">
    <h3> Question-10:</h3>
 <b>Write a code to display a 8*8 checkerboard pattern</h3> (starts with a 0 and alternates between 0 and 1).</b>
</div>

In [18]:
Z = np.zeros((8,8), dtype=int)     # Creating an empty 8X8 array
Z[::2, 1::2] = 1                   # Fills every alternate column correctly starting with 0
Z[1::2, ::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


<div class="alert alert-warning ">
    <h3> Question-11:</h3>
 <b>Compute the matrix product of 4X2 and 2X4 matrix.</b>
</div>

In [19]:
a1 = np.array([[1,5], [7,9], [1,0], [0,1]])
a2 = np.array([[5,0,5,1], [1,1,1,0]])
a1

array([[1, 5],
       [7, 9],
       [1, 0],
       [0, 1]])

In [20]:
# Method - 1

a1.dot(a2)

array([[10,  5, 10,  1],
       [44,  9, 44,  7],
       [ 5,  0,  5,  1],
       [ 1,  1,  1,  0]])

In [21]:
# Method - 2

np.dot(a1, a2)

array([[10,  5, 10,  1],
       [44,  9, 44,  7],
       [ 5,  0,  5,  1],
       [ 1,  1,  1,  0]])

In [22]:
# Method - 3

a1 @ a2

array([[10,  5, 10,  1],
       [44,  9, 44,  7],
       [ 5,  0,  5,  1],
       [ 1,  1,  1,  0]])

<div class="alert alert-warning ">
    <h3> Question-12</h3>
 <b>Decode the output of the code below. </b>
</div>

In [23]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


<a href="https://stackoverflow.com/questions/42955201/python-numpy-range-and-sum-1"> Explanation </a>

<div class="alert alert-warning ">
<h3> Question-13</h3>
<b>Create a 5x5 matrix with row values ranging from 0 to 4. </b>
</div>

In [24]:
a3 = np.zeros((5,5))
a3 += np.arange(5)            
a3                     # Very good example of broadcasting where np.arange(5) was broadcast across all rows

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

<a href = "https://github.com/rougier/numpy-tutorial#introduction">Numpy Visual Tutorial and exercises Github</a>

<a href="https://github.com/rougier/numpy-100">100 exercises in Numpy</a>