In [1]:
import numpy as np

### 1. Creating Numpy arrays

##### There are 5 general mechanisms for creating arrays:
<ol>

<li>Conversion from other Python structures (e.g., lists, tuples) </li>

<li>Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)</li>

<li>Reading arrays from disk, either from standard or custom formats</li>

<li>Creating arrays from raw bytes through the use of strings or buffers</li>

<li>Use of special library functions (e.g., random)</li>

</ol>

#### a) Using inbuilt Python structures: 

In [2]:
li1 = [1, 5, 54, -25]
ar1 = np.array(li1)
print(type(ar1))
ar1

<class 'numpy.ndarray'>


array([  1,   5,  54, -25])

In [3]:
ar2 = np.array([[1,0,1], [-1,2,5], (5,7,99)])
ar2

array([[ 1,  0,  1],
       [-1,  2,  5],
       [ 5,  7, 99]])

#### b) Using inbuilt numpy array creation functions

In [4]:
ar3 = np.zeros(5, dtype='int8')
ar3

array([0, 0, 0, 0, 0], dtype=int8)

In [5]:
ar4 = np.zeros((5,3))                 # creates an array of zeros
ar4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
ar5 = np.ones((3,4), dtype='float16')    # creates an array of ones
ar5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float16)

In [7]:
ar6 = np.arange(5, 7, 0.3)            # start, stop, step
ar6

array([5. , 5.3, 5.6, 5.9, 6.2, 6.5, 6.8])

##### linspace() will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. 

In [8]:
ar6 = np.linspace(5, 7, 5)     
ar6

array([5. , 5.5, 6. , 6.5, 7. ])

<a href="https://numpy.org/devdocs/user/quickstart.html"> More Examples here! (Numpy quickstart)</a>

### 2. Some characteristics of numpy arrays

In [9]:
ar5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float16)

In [10]:
ar5.ndim

2

In [11]:
ar5.shape

(3, 4)

In [12]:
ar6

array([5. , 5.5, 6. , 6.5, 7. ])

In [13]:
ar6.dtype

dtype('float64')

In [14]:
ar2.size                # tells you the total number of elements of the array.

9

### 3. Adding, removing, sorting elements

In [15]:
print("ar5:\n",ar5)
print("\nar6:",ar6)

ar5:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

ar6: [5.  5.5 6.  6.5 7. ]


In [16]:
np.sort([0,5,2,4,2.5])

array([0. , 2. , 2.5, 4. , 5. ])

In [17]:
ar1

array([  1,   5,  54, -25])

In [18]:
np.concatenate((ar1, ar6))     # inputs must have same dimensions

array([  1. ,   5. ,  54. , -25. ,   5. ,   5.5,   6. ,   6.5,   7. ])

In [19]:
ar7 = np.array([[5,4], [0,-1]])
ar8 = np.array([[54,55]])
ar7

array([[ 5,  4],
       [ 0, -1]])

In [20]:
ar8

array([[54, 55]])

In [21]:
np.concatenate((ar7, ar8))

array([[ 5,  4],
       [ 0, -1],
       [54, 55]])

### 4. Can you reshape arrays?

arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [22]:
ar1

array([  1,   5,  54, -25])

In [23]:
ar1.reshape((2,2))

array([[  1,   5],
       [ 54, -25]])

In [24]:
ar7

array([[ 5,  4],
       [ 0, -1]])

In [25]:
ar7.T               # Used to get the transpose of an array

array([[ 5,  0],
       [ 4, -1]])

### 5. How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [26]:
ar9 = np.arange(2, 15)
ar9

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
ar9.shape

(13,)

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [28]:
ar9_col_vector = ar9[:, np.newaxis]
ar9_col_vector

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [29]:
ar9_col_vector.shape

(13, 1)

### 6. Indexing and Slicing

You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [30]:
ar10 = np.array([[1 , 12, 3, 40], [55, 6, -7, 18], [9, 10, -11, 12]])

In [31]:
ar10

array([[  1,  12,   3,  40],
       [ 55,   6,  -7,  18],
       [  9,  10, -11,  12]])

In [32]:
ar10[2:]

array([[  9,  10, -11,  12]])

You can very easily choose a certain subset of the array you are working with.

In [33]:
ar10[ar10>0]

array([ 1, 12,  3, 40, 55,  6, 18,  9, 10, 12])

You can also make use of the logical operators in order to return boolean values that specify whether or not the values in an array fulfill a certain condition. This can be useful with arrays that contain names or other categorical values.

In [34]:
ar10>15

array([[False, False, False,  True],
       [ True, False, False,  True],
       [False, False, False, False]])

#### Slicing ndarrays: creates a view, not a copy (unlike slicing built in sequence types).

In [35]:
ar9

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
elements = ar9[2:5]                     # Slicing few elements from the array
print(elements)
elements += 10
print(elements)

[4 5 6]
[14 15 16]


#### We will notice that making any changes in a part of the array is going to be reflected in the entire array.

In [37]:
ar9

array([ 2,  3, 14, 15, 16,  7,  8,  9, 10, 11, 12, 13, 14])

### 7. Basic array operations

In [38]:
ar1

array([  1,   5,  54, -25])

In [39]:
ar1 + np.ones(4)

array([  2.,   6.,  55., -24.])

In [40]:
ar10

array([[  1,  12,   3,  40],
       [ 55,   6,  -7,  18],
       [  9,  10, -11,  12]])

In [41]:
ar10.sum(axis=0)                       # Sums each column

array([ 65,  28, -15,  70])

In [42]:
ar2

array([[ 1,  0,  1],
       [-1,  2,  5],
       [ 5,  7, 99]])

In [43]:
ar2.min(axis=1)                       # Finds the minimum in each row

array([ 0, -1,  5])

In [44]:
ar11 = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
ar11

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [45]:
np.unique(ar11)                      # Returns all the unique elements from an array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

To get the indices of unique values in a NumPy array (an array of first index positions of unique values in the array), just pass the <i>return_index</i> argument in <b>np.unique()</b> as well as your array.

In [46]:
unique, index_u = np.unique(ar11, return_index=True)
print(unique)
print(index_u)

[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]


### 8. Flattening multidimensional arrays

There are two popular ways to flatten an array: <b>.flatten()</b> and <b>.ravel()</b>. The primary difference between the two is that the new array created using ravel() is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since ravel does not create a copy, it’s memory efficient.

In [47]:
ar7

array([[ 5,  4],
       [ 0, -1]])

In [48]:
ar7.flatten()

array([ 5,  4,  0, -1])

In [49]:
ar7.ravel()

array([ 5,  4,  0, -1])

When you use ravel, the changes you make to the new array will affect the parent array.

In [50]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [51]:
a2 = x.ravel()
a2[0] = 98
print(x)                         # Original array
print()
print(a2)                        # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[98  2  3  4  5  6  7  8  9 10 11 12]


## To get help for any function from the documentation just add a <b>"?"</b> at the end.

### Example:

In [54]:
np.concatenate?

Docstring:
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'same_kind'.

    .. versionadded:: 1.20.0

Returns